version: 2.1

jobs:
  lint-terraform:
    docker:
      - image: hashicorp/terraform:1.3.6
    working_directory: ~/project/terraform
    steps:
      - checkout:
          path: ~/project
      - run:
          name: "terraform init"
          command: |
            terraform init -backend=false
      - run:
          name: "terraform validate"
          command: |
            terraform validate
      - run:
          name: "terraform fmt check"
          command: |
            terraform fmt -recursive -check

  lint-markdown:
    docker:
      - image: cimg/node:20.19
    steps:
      - checkout
      - run:
          name: Install markdownlint-cli
          command: npm install markdownlint-cli
      - run:
          name: Lint Markdown files
          command: npx markdownlint "**/*.md"
  
  lint-bash:
    docker:
      - image: cimg/base:2025.09
    steps:
      - checkout
      - run:
          name: "Install shfmt and shellcheck"
          command: |
            sudo apt-get update
            sudo apt-get install -y shellcheck shfmt
      - run:
          name: "Check shell script formatting"
          command: |
            shfmt -d -i 2 *.sh
      - run:
          name: "Lint scripts with ShellCheck"
          command: |
            shellcheck *.sh

workflows:
  lint:
    jobs:
      - lint-terraform
      - lint-markdown
      - lint-bash
